language: php

php:
  - 7.3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq graphviz
  - composer self-update
  - composer install --prefer-source

install:
  - travis_retry composer update

before_script:
  - mkdir -p tests/files

script:
  - ./vendor/bin/codecept run
