language: php

sudo: required

php:
  - 7.3

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq graphviz
  - composer self-update
  - composer install --prefer-source

install:
  - travis_retry composer update $COMPOSER_OPTS

before_script:
  - mkdir -p tests/files

script:
  - ./vendor/bin/codecept run
